kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: ${project.artifactId}
  namespace: awespring
  labels:
    app: ${project.artifactId}
spec:
  nodeSelector: {}
  output:
    to:
      kind: DockerImage
      name: 'docker.io/sathishkr/usermaintenance:latest'
    pushSecret:
      name: dockerhub 
  resources:
    limits:
      cpu: '1'
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 500Mi
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: >-
          registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:latest
  postCommit: {}
  source:
    type: Binary
    binary: {}
  triggers: []
  runPolicy: Serial